---
title: "function_outline"
output: html_document
---

# libraries and dependencies
```{r, warning=F,message=F}
library(dplyr)
library(nimble)
library(nimbleNoBounds)
library(nimbleMacros)

source("/work/users/a/g/agfoes/P1/R/function_development/buildModelCode.R")
source("/work/users/a/g/agfoes/P1/R/function_development/nimbleInputs.R")
source("/work/users/a/g/agfoes/P1/R/function_development/dynamicglm.R")
source("/work/users/a/g/agfoes/P1/R/function_development/customSamplers.R")

source("/work/users/a/g/agfoes/P1/R/helpers/helpers_data.R")
```

# input
```{r}
outcome_formula <- y ~ x_1 + z_1 + z_2 + z_3
outcome_family <- gaussian(link = "identity")

covariate_formula <- x_1 ~ z_1 + z_2 + z_3
censored_covariate <- "x_1"
censoring_bounds <- c("CL", "CR")

data <- data.frame(
  y = c(1, 2, 3),
  z_1 = c(2, 3, 4),
  z_2 = c(3, 4, 5),
  z_3 = c(4, 5, 6),
  CL = c(5, 6, 7),
  CR = c(5, 7, 8)
)

list2env(data, envir = .GlobalEnv)

data <- datagen(n = 10)
data <- data.frame(
  Y = data$Y,
  Z1 = data$Z1,
  Z2 = data$Z2,
  Z3 = data$Z3,
  CL = data$CL,
  CR = data$CR
)
outcome_formula <- Y ~ X + Z1 + Z2 + Z3
covariate_formula <- X ~ Z1 + Z2 + Z3
censored_covariate <- "X"
censoring_bounds <- c("CL", "CR")
```

# parse model formulas and data into design matrices
```{r}
# remove variables in censored_covariate from outcome_formula and create new updated/observed outcome_formula
observed_formula <- update(
  outcome_formula,
  paste(". ~ . -", paste(censored_covariate, collapse = " - "))
)

outcome_mf <- model.frame(observed_formula, data = data)

Y <- model.response(outcome_mf)
Zy <- model.matrix(observed_formula, data = data) # automatically adds an intercept

Zx <- model.matrix(delete.response(terms(covariate_formula)),
                   data = data) # automatically adds an intercept

pzy <- dim(Zy)[2] # includes intercept + dim of supplied uncensored covariates
py <- pzy + 1 # add one for the censored covariate
pzx <- dim(Zx)[2]
```

# build nimble data, inits, and constants
```{r}

nimble_inputs <- nimbleInputs(CL = data$CL,
                              CR = data$CR,
                              Zy = Zy,
                              Zx = Zx,
                              Y = Y)

```


# build nimble model code depending on model formulas and families
```{r}
family_def <- "Gamma(link = 'log')"
model_code <- buildModelCode(family = as.character(family_def),
                             nobs = nimble_inputs$nobs,
                             ncen = nimble_inputs$ncen)
```

# configure, compile, build nimble model
```{r}
nimbleOptions(enableMacros = TRUE)

model <- nimbleModel(
  code = model_code,
  data = nimble_inputs$Ndata,
  constants = nimble_inputs$Nconstants,
  inits = nimble_inputs$Ninits
)


conf <- configureMCMC(model,
                      useConjugacy = TRUE)
conf$removeSamplers("beta")


sampler_type = "AF_slice"
if (family_def == "gaussian(link = 'identity')") {
  conf$addSampler(
    target = "beta",
    type = sampler_beta_normal_conjugate_block,
    control = list(
      pzy = pzy,
      ncen = as.integer(nimble_inputs$ncen),
      nobs = as.integer(nimble_inputs$nobs)
    )
  )
} else if (sampler_type == 'block') {

  conf$addSampler(
    target = "beta",
    type = 'RW_block',
    control = list(scale = 0.05, adaptInterval = 100)
  )
} else if (sampler_type == 'AF_slice') {
    
  conf$addSampler(
    target = "beta",
    type = 'AF_slice'
  )
}
  
conf$printMonitors()
conf$printSamplers("beta")
```


# run nimble model and get samples
```{r}
mcmc <- buildMCMC(conf)
Cmodel <- compileNimble(model)
Cmcmc <- compileNimble(mcmc, project = Cmodel)
  
runtime <- system.time({
  samples <- runMCMC(
    Cmcmc,
    niter = 100,
    nburnin = 40,
    thin = 1,
    nchains = 1,
    samplesAsCodaMCMC = TRUE
  )
})
```

# report summary statistics / return samples


