---
title: "function_test"
output: html_document
---

# libraries, packages, source function
```{r, warning=F, message=F}
library(dplyr)
library(nimble)
library(nimbleNoBounds)
library(nimbleMacros)

source("/work/users/a/g/agfoes/P1/R/function_development/BCCglm.R")
source("/work/users/a/g/agfoes/P1/R/function_development/customSamplers.R")
source("/work/users/a/g/agfoes/P1/R/helpers/helpers_data.R")
```

# generate data
```{r}
datagen_glm <- function(outcome = "normal",                                         # normal, gamma, neg binomial, bernoulli, poisson
                        link = "identity",
                        n = 100,                                                    # sample size
                        pzy = 3,
                        pzx = 3,
                        mu_z = c(0.8, 0.6, 0.2),
                        sd_z = c(1, 1, 1),
                        #p_z2 = 0.8,                                                 # observed covariate Z2 ~ bern(p_z2)
                        #mu_z3 = 5, sd_z3 = 1,                                       # mean and sd for observed covariate Z3 ~ N(mu_z3, sd_z3)
                        comps = 3, w = c(0.3, 0.5, 0.2),                            # number of components for mixture X|Z and probabilities for each component
                        gamma = matrix(c(0, 3, 1, 
                                         0, 1, 5, 
                                         0, 2, 2), 
                                       nrow = 3, byrow = TRUE)*365.25,              # linear coeff. for X|Z ~ N(Z*gamma, x_sd)
                        x_sd = c(0.5, 1, 1)*365.25,
                        beta_x = 0.4/365.25,                                        # coefficients for outcome linear predictor on X
                        beta_z = c(0.2, 0.1, 0.2),                                  # coefficients for outcome linear predictor on Z
                        tau = 1,                                                    # outcome precision parameter
                        beta_omega = matrix(c(0, 0.5, 0.25,
                                              0, 0.25, 0.10),
                                            nrow = 2, byrow = TRUE),                # coefficients for visit generation observation category
                        alpha_start = c(5, 2, -0.5)*365.25,                         # parameter for start of observation window T0 ~ N(alpha * Z, sigma_start)
                        alpha_width = c(log(6*365.25), 0.25, -0.05),                # parameter for width of observation window log(W) ~ N(alpha * Z, sigma_width)
                        sigma_start = 1, sigma_width = 0.15,
                        jitter_sd = 30,                                             # sd for random noise added to each visit
                        rho = c(0.85, 0.9, 0.99),                                   # vector of probabilities for observing a visit
                        eps_obs = 350                                               # tolerance window for defining uncensored observations in X
) {
  
  ## observed covariates
  #Z1 <- rep(1, n)                                                               # intercept
  #Z2 <- rbinom(n = n, size = 1, p_z2)                                           # Z2 ~ binomial(p_z2)
  #Z3 <- rnorm(n, mean = mu_z3, sd = sd_z3)                                      # Z3 ~ normal(mu_z3, sd_z3)
  #Z <- cbind(Z1, Z2, Z3)
  
  Zy = matrix(data = NA, nrow = n, ncol = pzy)
  for (j in 1:pzy) {
    Zy[, j] <- rnorm(n, mu_z[j], sd_z[j])
  }
  
  Zx = Zy[, c(1:pzx)]
  
  ## censored covariate
  cluster <- sample(1:comps, n, replace = TRUE, prob = w)                       # sample X|Z cluster assignment from weights w
  means <- rowSums(Zx * gamma[cluster, 1:3])                                     # mean of X|Z determined by cluster assignment and gamma row
  X <- rnorm(n, mean = means, sd = x_sd[cluster])                               # X|Z ~ normal(mean[cluster], sd[cluster])
  
  ## outcome
  eta <- beta_x * X + Zy %*% beta_z
  
  if (outcome == "normal") {
    
    Y <- rnorm(n, mean = eta, sd = 1/sqrt(tau))
    
  } else if (outcome == "bernoulli") {
    
    theta <- plogis(eta)
    Y <- rbinom(n, size = 1, prob = theta)
    
  } else if (outcome == "gamma") {
    
    theta <- exp(eta)
    Y <- rgamma(n, shape = tau, rate = tau/theta)
    
  } else if (outcome == "poisson") {
    
    theta <- exp(eta)
    Y <- rpois(n, lambda = theta)
    
  } else if (outcome == "negbin") {
    
    theta <- exp(eta)
    Y <- rnbinom(n, size = tau, mu = theta)
    
  }
  
  ## probability of observing a visit
  omega_high <- as.numeric(Zy %*% beta_omega[1, ])                               # linear pred if subjects have high observation probability
  omega_med <- as.numeric(Zy %*% beta_omega[2, ])                                # linear pred if subjects have medium observation probability
  omega_low <- rep(0, n)                                                        # linear pred if subjects have low observation probability
  
  exp_omega <- cbind(exp(omega_high), exp(omega_med), exp(omega_low))           # exponentiate linear predictors
  pi_obs <- exp_omega / rowSums(exp_omega)                                      # calculate probabilities for observation probability assignment
  
  nu <- apply(pi_obs, 1, function(p) {                                          # sample observation categories with ^ probabilities per subject
    sample(1:3, size = 1, prob = p)
  })
  
  ## observation window
  T0 <- rnorm(n, mean = as.numeric(Zy %*% alpha_start), sd = sigma_start)        # observation window start visit
  W <- rlnorm(n, meanlog = as.numeric(Zy %*% alpha_width), sd = sigma_width)     # width of observation window
  T1 <- T0 + W
  
  ## storage
  CL <- CR <- numeric(n)
  DL <- DR <- Dobs <- integer(n)
  K_planned <- K_obs <- integer(n)
  V_star <- V_tilde <- V <- r <- vector('list', n)
  
  ## generate visit data
  for (i in seq_len(n)) {
    
    # initialize empty (zero-length) storage for visit vectors and observation indicator vector
    V_star_i <- V_tilde_i <- V_i <- numeric(0)       
    r_i <- integer(0)
    
    K_planned[i] <- floor(W[i] / 365.25)                                        # number of visits if none missed
    
    if (K_planned[i] > 0) {                         
      V_star_i <- T0[i] + 365.25 * seq_len(K_planned[i])                        # visits start as every year from observation window start
      
      V_tilde_i <- V_star_i + rnorm(K_planned[i], mean = 0, sd = jitter_sd)     # add noise to annual visit
      V_tilde_i <- sort(pmin(pmax(V_tilde_i, T0[i]), T1[i]))                    # sort visits in case ordering switched from added noise
      
      r_i <- rbinom(K_planned[i], size = 1, prob = rho[nu[i]])                  # sample observation indicator
      V_i <- V_tilde_i[r_i == 1]                                                # mask visits with observation idicator
    }
    
    # add in T0 as a forced observed visit (if a subject never comes to the enrollment visit they aren't in the study anyway so this makes sense)'
    V_star_i <- sort(c(T0[i], V_star_i))
    V_tilde_i <- sort(c(T0[i], V_tilde_i))
    r_i <- c(1, r_i)
    V_i <- sort(c(T0[i], V_i))
    
    K_obs[i] <- length(V_i)                                                     # number of observed visits
    V[[i]] <- V_i                                                               # observed visit vector
    V_star[[i]] <- V_star_i                                                     # planned visit vector
    V_tilde[[i]] <- V_tilde_i                                                   # jittered planned visit vector
    r[[i]] <- r_i                                                               # visit observation indicator vector
    
    ## covariate censoring indicators and endpoints
    
    if (X[i] < V_i[1]) {                                                        # if X is left censored
      CL[i] <- -Inf
      CR[i] <- V_i[1]
      DL[i] <- 1
    } else if (X[i] > V_i[K_obs[i]]) {                                          # if X is right censored
      CL[i] <- V_i[K_obs[i]]
      CR[i] <- Inf
      DR[i] <- 1
    } else {                                                                    # X either interval or uncensored
      right_idx <- which(V_i >= X[i])[1]                                        # smallest visit greater than X
      
      if (X[i] == V_i[right_idx]) {                                             # if X falls exactly on a visit
        CL[i] <- CR[i] <- X[i]
        Dobs[i] <- 1
      } else {                                                                  # if X is interval censored
        left <- V_i[right_idx - 1]
        right <- V_i[right_idx]
        
        if ((right - left) <= eps_obs) {                                        # if X is interval censored with endpoints within tolerance, define as uncensored
          CL[i] <- CR[i] <- X[i]
          Dobs[i] <- 1
        } else {
          CL[i] <- left
          CR[i] <- right
        }
      }
    }
  }
  
  return(list(
    outcome = as.character(outcome),
    
    Zx = Zx,
    Zy = Zy,
    X = X,
    Y = Y,
    cluster = cluster,
    
    T0 = T0,
    T1 = T1,
    W = W,
    nu = nu,
    K_planned = K_planned,
    K_obs = K_obs,
    V_star = V_star,
    V_tilde = V_tilde,
    V = V,
    r = r,
    rho = rho,
    
    CL = CL,
    CR = CR,
    DL = DL,
    DR = DR,
    Dobs = Dobs
  ))
}
```

