---
title: "custom_sampler_test"
output: html_document
---

The purpose of this script is to use a trivial regression scenario to test the custom joint conjugate sampler created for P1. This simulation will not use a DPMM model for the covariates. 

```{r, warning = FALSE, message = FALSE}
library(nimble)
library(truncnorm)
library(coda)
library(tidyverse)
library(nimbleNoBounds)
```


```{r}
sampler_beta_conjugate_block_obs_test <- nimbleFunction(
  contains = sampler_BASE,

  setup = function(model, mvSaved, target, control) {

    p <- control$p
    p_beta <- p + 1

    nobs <- as.integer(control$nobs)
    ncen <- as.integer(control$ncen)
    n <- nobs + ncen

    s_beta_inv <- inverse(
      model$beta_cov[1:p_beta, 1:p_beta]
    )

    beta_prior_num <- (s_beta_inv %*% asCol(model$beta_mean[1:p_beta])) # p_beta x 1 matrix (p_beta vector)

    calcNodes <- model$getDependencies(target)
  },

  run = function() {

    W <- matrix(0, nrow = n, ncol = p_beta)
    Y <- numeric(n)

    ## observed subjects
    if (nobs > 0) {
      for (k in 1:nobs) {

        W[k, 1] <- model$x_obs[k]

        for (j in 1:p) {
          W[k, j + 1] <- model$z_obs[k, j]
        }

        Y[k] <- model$y_obs[k]
      }
    }
    ## temporarily no censored subjects
    
    V_beta <- s_beta_inv + model$tau[1] * (t(W) %*% W) # p_beta x p_beta + p_beta x p_beta = p_beta x p_beta

    tWY <- (t(W) %*% Y) # should be p_beta x 1 matrix (p_beta vector)

    mu_beta_num <- (model$tau[1] * tWY + (beta_prior_num)) # p_beta vector + p_beta vector
    
    V_beta_inv <- inverse(V_beta) # p_beta x p_beta

    mu_beta <- (V_beta_inv %*% (mu_beta_num)) # p_beta vector
    
    ## draws
    V_beta_cholesky <- chol(V_beta)

    beta_new <- rmnorm_chol(
      1,
      mean = mu_beta[, 1],
      cholesky = V_beta_cholesky,
      prec_param = TRUE
    )

    
    model[[target]] <<- beta_new

    model$calculate(calcNodes)

    copy(
      from = model,
      to = mvSaved,
      row = 1,
      nodes = calcNodes,
      logProb = TRUE
    )
  },

  methods = list(
    reset = function() {}
  )
)
```

# data gen and nimble code
```{r}
n = 1000

# gen X, Z fully observed
X <- rnorm(n, mean = 0, sd = 1)
Z1 <- rep(1, n)
Z2 <- rbinom(n, size = 1, prob = 0.8)
Z3 <- rnorm(n, mean = 10, sd = 3)
cov = cbind(X, Z1, Z2, Z3)

# gen Y
truth <- c(0.7, 1, -1, 2)
Y <- cov %*% truth + rnorm(n, mean = 0, sd = 1)

code <- nimbleCode({

  beta[1:4] ~ dmnorm(
    mean = beta_mean[1:4],
    cov = beta_cov[1:4, 1:4]
  )
  
  tau ~ dgamma(1, 1)
  
  # outcome model
  for (i in 1:nobs) {
    eta[i] <- beta[1]*x_obs[i] + inprod(z_obs[i, 1:3], beta[2:4])
  
    y_obs[i] ~ dnorm(
      mean = eta[i],
      tau = tau
    )
  }
  
})

constants <- list(nobs = n,
                  beta_mean = rep(0, 4),
                  beta_cov = diag(c(1, 1, 1, 1), nrow = 4, ncol = 4))
data <- list(y_obs = Y[, 1],
             x_obs = cov[, 1],
             z_obs = cov[, 2:4])
inits <- list(tau = 1,
              beta = c(1, 1, 1, 1))
```


```{r}
mod <- nimbleModel(code = code,
                   data = data,
                   inits = inits,
                   constants = constants)

conf <- configureMCMC(mod, useConjugacy = TRUE)
conf$removeSampler("beta")
conf$addSampler(target = "beta", 
                type = sampler_beta_conjugate_block_obs_test,
                control = list(p = 3, nobs = 1000, ncen = 0))
conf$printSamplers()

mcmc <- buildMCMC(conf)
Cmodel <- compileNimble(mod)
Cmcmc <- compileNimble(mcmc, project = Cmodel)
samples <- runMCMC(
    Cmcmc,
    niter = 100000,
    nburnin = 40000,
    thin = 1,
    nchains = 1,
    samplesAsCodaMCMC = TRUE
  )
summary(samples)
```



